BEGIN;
insert into produccion.biodiversity
( specimen_id ,
    occurrence_id  ,
    "type" ,
    modified ,
    "language" ,
    rights ,
    rights_holder ,
    access_rights ,
    bibliographic_citation ,
    institution_id ,
    collection_id ,
    dataset_id ,
    institution_code ,
    collection_code ,
    dataset_name ,
    owner_institution_code ,
    basis_of_record ,
    information_withheld ,
    data_generalizations ,
    dynamic_properties ,
    catalog_number ,
    occurrence_details ,
    occurrence_remarks ,
    record_number ,
    recorded_by ,
    individual_id ,
    individual_count ,
    sex ,
    life_stage ,
    reproductive_condition ,
    behavior ,
    establishment_means ,
    occurrence_status ,
    preparations ,
    disposition ,
    other_catalog_numbers ,
    previous_identifications ,
    associated_media ,
    associated_references ,
    associated_occurrences ,
    associated_sequences ,
    associated_taxa ,
    event_id ,
    sampling_protocol ,
    sampling_effort ,
    event_date ,
    event_time ,
    start_day_of_year ,
    end_day_of_year ,
    "year" ,
    "month" ,
    "day" ,
    verbatim_event_date ,
    habitat ,
    field_number ,
    field_notes ,
    event_remarks ,
    location_id ,
    higher_geography_id ,
    higher_geography ,
    continent ,
    water_body ,
    island_group ,
    island ,
    country ,
    country_code ,
    state_province ,
    county ,
    municipality ,
    locality ,
    verbatim_locality ,
    verbatim_elevation ,
    minimum_elevation_in_meters ,
    maximum_elevation_in_meters ,
    verbatim_depth ,
    minimum_depth_in_meters ,
    maximum_depth_in_meters ,
    minimumdistance_abovesurface_in_meters ,
    maximumdistance_abovesurface_in_meters ,
    location_according_to ,
    location_remarks ,
    verbatim_coordinates ,
    verbatim_latitude ,
    verbatim_longitude ,
    verbatim_coordinate_system ,
    verbatim_srs ,
    decimal_latitude ,
    decimal_longitude ,
    geodetic_datum ,
    coordinate_uncertainty_in_meters ,
    coordinate_precision ,
    point_radius_spatial_fit ,
    footprint_wkt ,
    footprint_srs ,
    footprint_spatial_fit ,
    georeferenced_by ,
    georeference_protocol ,
    georeference_sources ,
    georeference_verification_status ,
    georeference_remarks ,
    geological_context_id ,
    earliest_eon_or_lowest_eonothem ,
    latest_eon_or_highest_eonothem ,
    earliest_era_or_lowest_erathem ,
    latest_era_or_highest_erathem ,
    earliest_period_or_lowest_system ,
    latest_period_or_highest_system ,
    earliest_epoch_or_lowest_series ,
    latest_epoch_or_highest_series ,
    earliest_age_or_lowest_stage ,
    latest_age_or_highest_stage ,
    lowest_biostratigraphic_zone ,
    highest_biostratigraphic_zone ,
    lithostratigraphic_terms ,
    "group" ,
    formation ,
    member ,
    bed ,
    identification_id ,
    identified_by ,
    date_identified ,
    identification_references ,
    identification_remarks ,
    identification_qualifier ,
    type_status ,
    taxon_id ,
    scientific_name_id ,
    accepted_name_usage_id ,
    parent_name_usage_id ,
    original_name_usage_id ,
    name_according_to_id ,
    name_published_in_id ,
    taxon_concept_id ,
    taxon_scientific_name ,
    scientific_name ,
    accepted_name_usage ,
    parent_name_usage ,
    original_name_usage ,
    name_according_to ,
    name_published_in ,
    higher_classification ,
    kingdom ,
    phylum ,
    class ,
    "order" ,
    family ,
    genus ,
    subgenus ,
    specific_epithet ,
    infraspecific_epithet ,
    taxon_rank ,
    verbatim_taxon_rank ,
    scientific_name_authorship ,
    vernacular_name ,
    nomenclatural_code ,
    taxonomic_status ,
    nomenclatural_status ,
    taxon_remarks ,
    source ,
    solr_event_date_start ,
    solr_event_date_finish ,
    solr_date_identified ,
    solr_modified ,
    created ,
    created_user ,
    lastmodified,
    lastmodified_user ,
    biological_group )
select
"biodiversity_id",
"occurrence_id",
"type",
"modified",
"language",
null::text as "rights",
"rights_holder",
"access_rights",
"bibliographic_citation",
"institution_id",
"collection_id",
"dataset_id",
"institution_code",
"collection_code",
"dataset_name",
"owner_institution_code",
"basis_of_record",
"information_withheld",
"data_generalizations",
"dynamic_properties",
"catalog_number",
null::text as "occurrence_details",
"occurrence_remarks",
"record_number",
"recorded_by",
null::text as "individual_id",
"individual_count"::integer,
"sex",
"life_stage",
"reproductive_condition",
"behavior",
"establishment_means",
"occurrence_status",
"preparations",
"disposition",
"other_catalog_numbers",
"previous_identifications",
"associated_media",
"associated_references",
"associated_occurrences",
"associated_sequences",
"associated_taxa",
"event_id",
"sampling_protocol",
"sampling_effort",
"event_date",
"event_time",
"start_day_of_year"::integer,
"end_day_of_year"::integer,
"year"::integer,
"month"::integer,
"day"::integer,
"verbatim_event_date",
"habitat",
"field_number",
"field_notes",
"event_remarks",
"location_id",
"higher_geography_id",
"higher_geography",
"continent",
"water_body",
"island_group",
"island",
"country",
"country_code",
"state_province",
"county",
"municipality",
"locality",
"verbatim_locality",
"verbatim_elevation",
"minimum_elevation_in_meters"::numeric,
"maximum_elevation_in_meters"::numeric,
"verbatim_depth",
"minimum_depth_in_meters"::numeric,
"maximum_depth_in_meters"::numeric,
minimum_distance_above_surface_in_meters::numeric as "minimumdistance_abovesurface_in_meters" ,
maximum_distance_above_surface_in_meters::numeric as  "maximumdistance_abovesurface_in_meters",
"location_according_to",
"location_remarks",
"verbatim_coordinates",
"verbatim_latitude",
"verbatim_longitude",
"verbatim_coordinate_system",
"verbatim_srs",
"decimal_latitude"::numeric,
"decimal_longitude"::numeric,
"geodetic_datum",
"coordinate_uncertainty_in_meters"::numeric,
"coordinate_precision"::numeric,
"point_radius_spatial_fit"::numeric,
"footprint_wkt",
"footprint_srs",
"footprint_spatial_fit"::numeric,
"georeferenced_by",
"georeference_protocol",
"georeference_sources",
"georeference_verification_status",
"georeference_remarks",
"geological_context_id",
"earliest_eon_or_lowest_eonothem",
"latest_eon_or_highest_eonothem",
"earliest_era_or_lowest_erathem",
"latest_era_or_highest_erathem",
"earliest_period_or_lowest_system",
"latest_period_or_highest_system",
"earliest_epoch_or_lowest_series",
"latest_epoch_or_highest_series",
"earliest_age_or_lowest_stage",
"latest_age_or_highest_stage",
"lowest_biostratigraphic_zone",
"highest_biostratigraphic_zone",
"lithostratigraphic_terms",
"group",
"formation",
"member",
"bed",
"identification_id",
"identified_by",
"date_identified",
"identification_references",
"identification_remarks",
"identification_qualifier",
"type_status",
"taxon_id",
"scientific_name_id",
"accepted_name_usage_id",
"parent_name_usage_id",
"original_name_usage_id",
"name_according_to_id",
"name_published_in_id",
"taxon_concept_id",
"taxon_scientific_name",
"scientific_name",
"accepted_name_usage",
"parent_name_usage",
"original_name_usage",
"name_according_to",
"name_published_in",
"higher_classification",
"kingdom",
"phylum",
"class",
"order",
"family",
"genus",
"subgenus",
"specific_epithet",
"infraspecific_epithet",
"taxon_rank",
"verbatim_taxon_rank",
"scientific_name_authorship",
"vernacular_name",
"nomenclatural_code",
"taxonomic_status",
"nomenclatural_status",
"taxon_remarks",
"source",
"solr_event_date_start"::date,
"solr_event_date_finish"::date,
"solr_date_identified"::date,
"solr_modified"::date,
"_creation"::timestamp(6),
"_creation_user",
"_last_modified"::timestamp(6),
"_last_modified_user",
"biological_group"
 from ccud_pda2.biodiversity
/* 
where
( ccud_pda2.biodiversity.dataset_id  = 'IBUNAM:MEXU:AL' or ccud_pda2.biodiversity.dataset_id  = 'IBUNAM:MEXU:FS'  or ccud_pda2.biodiversity.dataset_id  = 'IBUNAM:MEXU:FU' or ccud_pda2.biodiversity.dataset_id  = 'IBUNAM:MEXU:LI' or ccud_pda2.biodiversity.dataset_id  = 'IBUNAM:MEXU:XI' ) and
ccud_pda2.biodiversity.catalog_number_qi = '1' AND ((ccud_pda2.biodiversity.catalog_number_qi = (1)::numeric)

AND  (ccud_pda2.biodiversity.family_qi >= 0.6)
AND  ((ccud_pda2.biodiversity.genus_qi >= 0.6) OR (COALESCE(ccud_pda2.biodiversity.genus_qi, (0)::numeric) = (0)::numeric))
AND ((ccud_pda2.biodiversity.specific_epithet_qi >= 0.6) OR (COALESCE(ccud_pda2.biodiversity.specific_epithet_qi, (0)::numeric) = (0)::numeric))
AND ((ccud_pda2.biodiversity.infraspecific_epithet_qi >= 0.6) OR (COALESCE(ccud_pda2.biodiversity.infraspecific_epithet_qi, (0)::numeric) = (0)::numeric))
AND ((ccud_pda2.biodiversity.scientific_name_authorship_conabio_qi >= 0.6) OR (COALESCE(ccud_pda2.biodiversity.scientific_name_authorship_conabio_qi, (0)::numeric) = (0)::numeric))
AND  (ccud_pda2.biodiversity.country_qi >= 0.6) AND ((ccud_pda2.biodiversity.state_province_qi >= 0.6) OR (COALESCE(ccud_pda2.biodiversity.state_province_qi, (0)::numeric) = (0)::numeric)));
*/
COMMIT;
